### PR TITLE
Ssr theme with cookies

### LINKED ISSUE #323: SSR is broken
localhost body:

```html
<body>
  <div id="root"></div>
</body>
```

### PR DESCRIPTION
**Pull request by lee-chase**
Fixes #323 

This uses cookies pure CSS to set the theming. 

The result
+ SSR works
- Small judder as font/styles applied. Only if you spam the refresh and hold shift to force a hard refresh.
- No longer using GlobalTheme/Theme components. Using them provides context in code allowing a component to know the current theme and if it is light or dark.

One suggestion was to pre-load fonts. I did not add this as it reduced the performance to 99.

### CODE REVIEW

File: src/test/test-utils.jsx [hunk 1]
```diff
@@ -64,3 +45,5 @@ export function renderWithoutProviders(ui, renderOptions = {}) {
 
   return rtlRender(ui, { wrapper: Wrapper, ...renderOptions });
 }
+
+// Made with Bob
```
Comment (rodet) [inline src/test/test-utils.jsx]: Oops, need to remove that one

**Review by rodet — APPROVED** [review]
Good to merge aside from the small marker to remove :D Let's continue the optimization with the fonts separately.
